### PR TITLE
Update mobile UA as the existing one doesn't seem to work anymore

### PR DESCRIPTION
**Pull request by mooons**
The existing mobile user-agent stopped working on my end.

Here I replaced it with one from an iPhone running latest iOS 15 beta, which works for me.

Please kindly review. :)

### CODE REVIEW

**Comment by tmxkn1** [comment]
Hi,

Thanks a lot. 

It's interesting the android user agent does not work for you. I think it works for me and others. May I ask what platform are you using the extension? I'm curious why this could happen and if Android did not work for you, iPhone may not work for others.

Cheers

**Comment by mooons** [comment]
> Hi,
> 
> Thanks a lot.
> 
> It's interesting the android user agent does not work for you. I think it works for me and others. May I ask what platform are you using the extension? I'm curious why this could happen and if Android did not work for you, iPhone may not work for others.
> 
> Cheers

Thanks @tmxkn1 ! I tried to change mobile UA back today. Now it works for me (again).

I have been able to use this as-is without issues for months until yesterday. I'm running this on Chrome 92.0.4515.159 on my Mac. I regularly pull from the repo to keep the code up-to-date and am on the latest commit when I had the issue.

The symptom yesterday was that when I click "Check Now". The extension icon turned yellow even though Mobile search progress is at 0/100. I tried to click "Check Now" multiple times but it would just turn yellow immediately. Also tried to reload the extension in dev mode, turn the extension off and on. No luck. I then changed the mobile UA, reloaded the extension. And it started working again for me.

So it might be some other one-off bugs that isn't really related to the UA.

Closing this PR.

**Comment by tmxkn1** [comment]
Looks like we are now all affected by the problem... and this fix seems working. I need another day to confirm it as I haven't got a chance to test it.

**Comment by tmxkn1** [comment]
Looks like you have deleted your repo hence can't be reopened. Please submit another one for credit. Meanwhile, I will push a quick fix branch for others to test.

**Comment by mooons** [comment]
> Looks like you have deleted your repo hence can't be reopened. Please submit another one for credit. Meanwhile, I will push a quick fix branch for others to test.

Yeah I will recover the repo with the commit. Pls confirm if this works on your end.

I'm wondering if there are some other checks than UA involved in mobile Edge search progression now.
I tried this morning with the older UA, didn't work, switched to the new UA, still didn't work (reloaded the extension, off-and-on; but didn't restart Chrome).

**Pull request closed without merging**
