### PR TITLE
Update useragents.json

### PR DESCRIPTION
**Pull request by XxBAJNOKxX**
Edge Useragent update

### CODE REVIEW

**Comment by tmxkn1** [comment]
Hi, please keep UA's URL the same. However, feel free to do so with your fork. If you want to contribute to the user agents, it is best to do so via the updated user agent repository :). I have added you as a maintainer so you can pull and merge freely. The useragents in this repo will only be updated if they are super outdated and no longer work. They still work for me and others at the moment.

**Comment by XxBAJNOKxX** [comment]
Sorry, I forgot to close the pull request.

**Comment by XxBAJNOKxX** [comment]
I have some questions, would it be possible to talk somewhere other than this pull req?

**Comment by tmxkn1** [comment]
My discord alphamoon__

**Pull request closed without merging**
